### ISSUE TITLE
npm package update

### ISSUE THREAD

**Issue by ryankelley** [jeef3/teamcity#5]
Was wondering if you could please update the npm package for teamcity. Thank You!

**Comment by jeef3** [comment]
This is something I'v been putting off for a while because the changes since last release are breaking and incomplete.

I could probably publish as like a 1.0-alpha?

**Comment by ryankelley** [comment]
That would be pretty awesome, would it be helpful if we published it as a different package?

**Comment by jeef3** [comment]
@ryankelley okay, this is my first time publishing non-release packages to NPM, so hope it works. You should be able to `npm install teamcity@1.0.0-preview`.

**Comment by jeef3** [comment]
@ryankelley, let me know how you get on and I'll close this issue :smile:

**Comment by jeef3** [comment]
Haven't heard back, so assuming it's working :+1:
