### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by fjakop** [jeef3/teamcity#6]
When I try to use your example
```
// Get some builds
teamcity.builds(1234, function (build) {
  console.log(build); --> yields undefined
})

teamcity.builds(1234, function (err, build) {
  console.log(build); --> yields the expected result
})

```

**Comment by jeef3** [comment]
Thanks @fjakop! You're right, looks like a typo in the docs. Since master is already at 1.0 prerelease this may need to be fixed on a separate branch.

**Comment by fjakop** [comment]
btw. is the 1.0 preview working? When I try to use it, even require fails with "Builds is not defined".

**Comment by jeef3** [comment]
It should work, but it will have massive holes in it (like pre 1 does). The API for 1.0 is very different though.

**Comment by fjakop** [comment]
seem I'm to blunt or it does not work, I've installed via `npm install teamcity@1.0.0-preview`, all is fine. My test fails at requiring teamcity:

    describe('teamcity api test', function () {
        it('should require api', function (done) {
            var teamcity = require('teamcity');
            done();
        });
    });

```
#> mocha test-tc.js

  teamcity api test
    1) should require api


  0 passing (208ms)
  1 failing

  1) teamcity api test should require api:
     ReferenceError: Builds is not defined
      at /tmp/mymodule/node_modules/teamcity/lib/teamcity.js:37:37
      at Object.<anonymous> (/tmp/mymodule/node_modules/teamcity/lib/teamcity.js:154:5)
      at Object.<anonymous> (/tmp/mymodule/node_modules/teamcity/lib/teamcity.js:158:4)
      at require (internal/module.js:12:17)
```

Can you provide some hint please?

**Comment by jeef3** [comment]
Okay yeah, that's broken.

I'm currently only using `0.0.3` and `0.0.6` in my projects. The TeamCity API is so massive that I've only implemented the bits I was using. I started restructuring it to try and follow their docs a bit more closely, the only reason I released the `1.0.0-preview` was because someone requested it, so I assumed it was working for them... I guess not :open_mouth: 

To be honest, I haven't sunk much time into it recently as the demand just hasn't been there. The parts of the API I need are working, and no one else has said otherwise.

If the interest is there, I'm keen to start up a discussion on the future of `1.0`?

**Comment by fjakop** [comment]
The reason I asked is because I've added some locator dimensions for TC 9 and prbably will add some features, as I need them.
My personal problem is I'm a Java dev and new to JS/Coffee, so it's hard to understand why something fails. My project now ist based on `0.0.7` but it seems not right for me to stay there and place PRs for an old version, so yes, there's need and interest by ma.

**Comment by jeef3** [comment]
@fjakop I've just quickly done an update that should *hopefully* help with the module not loading when trying to use `1.0.0-preview`. I haven't published it yet though, but you should be able to get it directly:

```
npm install --save jeef3/teamcity#62bb309
```

https://docs.npmjs.com/cli/install

**Comment by fjakop** [comment]
Thanks, it's better than before, but now it's stuck with
```
var buildTypesOfProject = teamcity
                        .buildTypeLocator();
```
resulting in
`TypeError: teamcity.buildTypeLocator is not a function`

**Comment by jeef3** [comment]
@fjakop Hmm, that *should* work fine.

I'm going to close this issue, since it's going a bit beyond that, and I've opened up a new one: #7 I'll try and use that as a running thread for an eventual 1.0 release.

If you were able to perhaps provide some more context on that new issue?
